version: '3.8'

services:
  auth-database:
    image: mongo:latest
    container_name: mongo-database
    ports:
      - "27017:27017"
    healthcheck:
      test: [ "CMD-SHELL", "mongo --eval 'db.stats().ok'" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - mongo_data:/data/db

  auth-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auth-service
    ports:
      - "9005:9005"
    environment:
      REGISTRY_SERVER: service-registry
      DB_SERVER: auth-database
      MANAGEMENT_METRICS_TAGS_APPLICATION: auth-service
      OTEL_EXPORTER_OTLP_ENDPOINT: http://tempo:4317
      OTEL_SERVICE_NAME: auth-service
      OTEL_RESOURCE_ATTRIBUTES: compose_service=auth-service
      OTEL_METRICS_EXPORTER: none
    depends_on:
      - auth-database

volumes:
  mongo_data:
